version: "3.7"

services:
    
    mongo_tdd_image_tests:
        image: mongo:4.1.8-xenial
        container_name: db_image_test
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=sammy
            - MONGO_INITDB_ROOT_PASSWORD=your_password
    
    service_tests:
        image: tdd_sample:latest
        container_name: service-image-test
        depends_on: 
            - mongo_tdd_image_tests
        ports:
            - 3000:3000
        environment:
            - MONGO_USERNAME=sammy
            - MONGO_PASSWORD=your_password
            - MONGO_PORT=27017
            - MONGO_DB=sharkinfo
            - MONGO_HOSTNAME=mongo_tdd_image_tests
        command: "yarn test-image"
            

        